shop/carts/urls.py
from django.urls import path
from carts import views
from django.conf.urls.static import static

app_name = 'carts'
    
urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from shop import settings
from django.contrib.auth.views import PasswordResetConfirmView
    
urlpatterns = [
    path('MEGAadmin/', admin.site.urls),
    path('', views.home, name='home'),
    path('faq', views.faq, name='faq'),
    path('registration', views.registration, name='registration'),
    path('login', views.login, name='login'),
    path('profile', views.profile, name='profile'),
    path('сhangePass', views.сhangePass, name='сhangePass'),
    path('password_reset/', views.passwordReset, name='password_reset'),
    path('password_reset/done/', views.home, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.home, name='password_reset_complete'),
    path('userInfo', views.userInfo, name='userInfo'),
    path('logout', views.logout, name='logout'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('category/<slug:category_slug>/', views.category, name='category'),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class categories(models.Model):
    name = models.CharField('Категория', max_length=100, unique=True)
    slug = models.SlugField('URL', max_length=100, unique=True, blank=True, null=True)

    class Meta:
        db_table = 'categories'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class products(models.Model):
    product_name = models.CharField('Название', max_length=100, unique=True)
    description = models.TextField('Описание', blank=True, null=True)
    img = models.ImageField('Изображение', upload_to='images', blank=True, null=True)
    img2 = models.ImageField('Изображение2', upload_to='images', blank=True, null=True)
    img3 = models.ImageField('Изображение3', upload_to='images', blank=True, null=True)
    img4 = models.ImageField('Изображение4', upload_to='images', blank=True, null=True)
    img5 = models.ImageField('Изображение5', upload_to='images', blank=True, null=True)
    product_price = models.DecimalField('Цена', max_digits=7, decimal_places=2, default=0.00)
    discount = models.DecimalField('Скидка', max_digits=7, decimal_places=2, default=0.00)
    quantity = models.PositiveIntegerField('Количество', default=0)
    slug = models.SlugField('URL', max_length=100, unique=True, blank=True, null=True)
    category = models.ForeignKey(to=categories, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.product_name
    
    def display_id(self):
        return f"{self.id:03}"
    
    def sell_price(self):
        if self.discount:
            return round(self.product_price - self.product_price*self.discount/100)

        return self.product_price
    

    def usd_price(self):        
        return round(float(self.product_price) * 0.01, 2)

    def usd_sell_price(self):
        if self.discount:
            return round(float(self.product_price) * 0.01 - float(self.product_price) * 0.01 * float(self.discount)/100, 2)
        
        return round(float(self.product_price) * 0.01, 2)
    


       
    class Meta:
        db_table = 'products'
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class User(AbstractUser):
    image = models.ImageField('Аватар', upload_to='images', blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    region = models.CharField(max_length=100, null=True, blank=True, verbose_name="Область/край/регион")
    city = models.CharField(max_length=100, null=True, blank=True, verbose_name="Город")
    street = models.CharField(max_length=100, null=True, blank=True, verbose_name="Улица/дом/квартира")
    postcode = models.CharField(max_length=100, null=True, blank=True, verbose_name="Почтовый индекс")

    def __str__(self):
        return self.username
    
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

shop/orders/models.py
from django.db import models

from main.models import User, products



class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_usd_price(self):
        return round(float(sum(cart.products_price() for cart in self)) * 0.01, 2)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name="Требуется доставка")
    region = models.CharField(max_length=100, null=True, blank=True, verbose_name="Область/край/регион")
    city = models.CharField(max_length=100, null=True, blank=True, verbose_name="Город")
    street = models.CharField(max_length=100, null=True, blank=True, verbose_name="Улица/дом/квартира")
    postcode = models.CharField(max_length=100, null=True, blank=True, verbose_name="Почтовый индекс")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при получении")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ("id",)

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"
        ordering = ("id",)

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

shop/main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, UserChangeForm
from main.models import User

class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username",
            "password1",
            "password2",
        )
    
    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class CustomPasswordChangeForm(PasswordChangeForm):

    old_password = forms.CharField()
    new_password1 = forms.CharField()
    new_password2 = forms.CharField()


class UserInfoForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "region", "city", "street", "postcode",
        )

class PasswordResetForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("email",)
    email = forms.CharField()

class PasswordResetConfirmForm(forms.ModelForm):

    new_password1 = forms.CharField()
    new_password2 = forms.CharField()

shop/orders/forms.py
import re
from django import forms

class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    email = forms.CharField()
    phone_number = forms.CharField()
    region = forms.CharField()
    city = forms.CharField()
    street = forms.CharField()
    postcode = forms.CharField()
    
    
def clean_phone_number(self):
       data = self.cleaned_data['phone_number']
       if not data.isdigit():
           raise forms.ValidationError("Номер телефона должен содержать только цифры")
       
       pattern = re.compile(r'^\d{10}$')
       if not pattern.match(data):
           raise forms.ValidationError("Неверный формат номера")
       return data

shop/main/templates/main/base.html
{% load static %}
{% load carts_tags %}

{% user_carts request as carts %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="imagetoolbar" content="no"/>
    <title>{{ title }}</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,500,700" rel="stylesheet">
    <link rel="icon" href="{% static 'main/img/icon.svg' %}" type="image/svg+xml">
    <link rel="stylesheet" href="{% static 'main/css/home.css' %}">
</head>
<body class="light">
    <div class="LogoBackground"></div>
    <header class="header">
        <div class="Logo">
            <a href="{% url 'home' %}">
                <p class="logoLeft">MEGA</p>
                <p class="logoRight">SHOP</p>
            </a>
        </div>
        <div class="menu">
            <div class="menu1">
                <ul class="menu__nav">
                    {% for category in categories %}
                    <li class="menu_item">
                        <a href="{% url 'category' category.slug %}" >{{category.name}}</a>
                    </li>
                    {% endfor %}
                    {% block faq %}
                        <li class="menu_item">
                            <a href="{% url 'faq' %}">FAQ</a>
                        </li>
                    {% endblock faq %}
                </ul>
            </div>
        </div>
        <div class="options">
            <ul class="options__nav">
                {% if not user.is_authenticated %}
                    <li class="options__item">
                        {% block loginBtn %}
                            <button onclick="showLogin()" class="loginBtn">
                                <img src="{% static 'main/img/profile.svg' %}">
                            </button>
                        {% endblock  %}
                    </li>     
                {% else %}
                    {% if not order %}
                        <li class="options__item">
                            {% block cartBtn %}
                                <button onclick="showCart()" class="cartBtn">
                                    <img src="{% static 'main/img/cart.svg' %}">
                                    <span id="goods-in-cart-count">{{ carts.total_quantity }}</span>
                                </button>
                            {% endblock  %}
                        </li>
                    {% endif %}
                    {% block profile %}
                        <a href="{% url 'profile' %}">
                            <li class="options__item">
                                <img src="{% static 'main/img/profile.svg' %}">
                            </li>
                        </a>
                    {% endblock  %}
                {% endif %}
            </ul>
        </div>
        <form id="cart_items_container" class="modal">
            <div class="modal-content">
                <span class="close" onclick="closeCart()">×</span>
                    <div class="headName">Корзина</div>
                    <div id="cart_items">
                        {% include "carts/includes/included_cart.html" %}
                    </div>
            </div>
        </form>
            <form action="{% url 'login' %}" method="post" id="loginModal" class="modal">
                <div class="modal-content">
                    <div class="close" onclick="closeLogin()">×</div>
                    <div class="headName">Вход в аккаунт</div>
                    <div class="field-holdeer">
                        <input type="text" class="form-control login"
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                        name="username" id="id_username" required>
                        <label for="id_username" class="form-label login">Имя пользователя</label>
                    </div>
                    <div class="field-holdeer">
                        <input type="password" class="form-control login" 
                        value="{% if form.password.value %}{{ form.password.value }}{% endif %}" 
                        name="password" id="id_password" required>
                        <label for="id_password" class="form-label login">Пароль</label>
                    </div>
                    <button class="enterLogin">Войти</button>
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                        <p id="ErrorForm">{{ form.non_field_errors }}</p>
                    {% endif %}

                    <div id="downRegistr">
                        <a onclick="showReset()" class="loginBtn">Забыли пароль?</a>
                    </div>

                    <div id="downRegistr">Нет аккаунта?
                        <a onclick="showReg()" class="loginBtn">Зарегистрироваться</a>
                    </div>
                </div>
            </form>

            <form action="{% url 'registration' %}" method="post" id="registerModal" class="modal">
                <div class="modal-content">
                    <div class="close" onclick="closeReg()">×</div>
                    <div class="headName">Регистрация</div>
                    <div class="field-holdeer">
                        <input type="text" class="form-control login"
                        name="username" id="id_username1" required
                        readonly onfocus="this.removeAttribute('readonly')">
                        <label for="id_username1" class="form-label login">Имя пользователя</label>
                    </div>
                    {% if user.is_authenticated %}
                    {% else %}
                        {% if formReg.username.errors %}
                            <p id="ErrorForm2">{{ formReg.username.errors }}</p>
                        {% endif %}
                    {% endif %}
        
                    <div class="field-holdeer">   
                        <input type="password" class="form-control login" id="id_password1" 
                            name="password1" required>
                        <label for="id_password1" class="form-label login">Пароль</label>
                    </div>

                    {% if user.is_authenticated %}
                    {% else %}
                        {% if formReg.password1.errors %}
                            <p id="ErrorForm2">{{ formReg.password1.errors }}</p>
                        {% endif %}
                    {% endif %}
        
                    <div class="field-holdeer">
                        <input type="password" class="form-control login" id="id_password2"
                            name="password2" required>
                        <label for="id_password2" class="form-label login">Подтверждение пароля</label>
                    </div>
                    
                    {% if user.is_authenticated %}
                    {% else %}
                        {% if formReg.password2.errors %}
                            <p id="ErrorForm2">{{ formReg.password2.errors }}</p>
                        {% endif %}
                    {% endif %}

                    {% if user.is_authenticated %}
                    {% else %}
                    {% if formReg.non_field_errors %}
                        <p id="ErrorForm2">{{ formReg.non_field_errors }}</p>
                    {% endif %}
                    {% endif %}
                        
                    <button class="enterLogin">Продолжить</button>
                    {% csrf_token %}
                    <div id="downRegistr">Есть аккаунт?
                        <a onclick="showLogin()" class="loginBtn">Войти</a>
                    </div>
                </div>
            </form>

            <form action="{% url 'password_reset' %}" method="post" id="resetModal" class="modal">
                <div class="modal-content">
                    <div class="close" onclick="closeReset()">×</div>
                    <div class="headName">Введите почту</div>
                    <div class="field-holdeer">
                        <input type="text" class="form-control login" 
                        value="{% if password_reset_form.email.value %}{{ password_reset_form.email.value }}{% endif %}" 
                        name="email" id="id_email" required>
                        <label for="id_email" class="form-label login">Почта</label>
                    </div>
                    {% if user.is_authenticated %}
                    {% else %}
                        {% if password_reset_form.email.errors %}
                            <p id="ErrorForm3">{{ password_reset_form.email.errors }}</p>
                        {% endif %}
                    {% endif %}
        

                    {% if user.is_authenticated %}
                    {% else %}
                    {% if password_reset_form.non_field_errors %}
                        <p id="ErrorForm3">{{ password_reset_form.non_field_errors }}</p>
                    {% endif %}
                    {% endif %}
                        
                    <button class="enterLogin">Отправить</button>
                    {% csrf_token %}
                    <div id="downRegistr">
                        <a onclick="backReset()" class="loginBtn">Назад</a>
                    </div>
                </div>
            </form>
        <script src="{% static 'main/js/jquery/jquery-3.7.1.min.js' %}"></script>
        <script src="{% static 'main/js/jquery-ajax.js' %}"></script>
        <script src="{% static 'main/js/main.js' %}"></script>
        <script src="{% static 'main/js/theme.js' %}"></script>
        <script src="{% static 'main/js/currency.js' %}"></script>
        {% block js %}{% endblock  %}
    </header>
    <main>
        {% block content %}{% endblock  %}
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div id="jq-notification" class="message">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <div id="jq-notification" class="message"></div>
        {% endif %}
    </main>
    <footer>
        <p>МОЯ КОМПАНИЯ</p>
    </footer>
</body>
</html>

shop/main/templates/main/faq.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
    <p>Ответы на вопросы</p>
{% endblock  %}

shop/main/templates/main/home.html
{% extends "main/base.html" %}
{% load static %}


{% block content %}
    <div class="InfoContainer">
        <div>
            <h2 class="InfoText">ГЛАВНАЯ</h2>
        </div>
        <div class="line" id="line1"></div>
        <div class="line" id="line2"></div>
    </div>
{% endblock  %}

shop/main/templates/main/password_reset_confirm.html
{% extends 'main/base.html' %}
{% load static %}

{% block faq %}{% endblock  %}
{% block loginBtn %}{% endblock  %}
{% block content %}


<form method="post" class="ResetModal">
    {% csrf_token %}
    <div class="field-holdeer">
        <input type="password" class="form-control login"  
        name="new_password1" id="new_password1" required>
        <label for="new_password1" class="form-label login">Новый пароль:</label>
    </div>
    <div class="field-holdeer">
        <input type="password" class="form-control login"  
        name="new_password2" id="new_password2" required>
        <label for="new_password2" class="form-label login">Подтвердите пароль:</label>
    </div>

    <button class="enterLogin" type="submit">Сбросить пароль</button>
</form>

{% endblock %}

shop/main/templates/main/profile.html
{% extends "main/base.html" %}
{% load static %}

{% block profile %}{% endblock  %}
{% block content %}
    <div class="profileContainer">

        <div class="profileNav">

            <div class="profileTitle">Навигация</div>
            <div class="profileNavContainer">
                <a href="#" class="nav navPersnInf activeNav">Персональные данные</a>
                <a href="#" class="nav navMyOrders">Мои заказы</a>
                <a href="#" class="nav navPasswrd">Смена пароля</a>
                <a href="#" class="nav navAdditSett">Дополнительные <br>настройки</a>
                <a href="{% url 'logout' %}" class="exit">Выход из аккаунта</a>
            </div>

        </div>


        <div class="tab profileInf activeTab">
            <div class="profileTitle">Данные пользователя</div>

            <form action="{% url 'userInfo' %}" method="post" id="loginModal" class="profileInfContainer">

                <div class="infBlock">
                    <label for="id_first_name" class="infTitle">Имя</label>
                    <input type="text" class="infInput" 
                    value="{% if request.user.first_name %}{{ request.user.first_name }}{% endif %}"
                    name="first_name" id="id_first_name" required placeholder="Введите имя">
                </div>

                <div class="infBlock">
                    <label for="id_last_name" class="infTitle">Фамилия</label>
                    <input type="text" class="infInput"  
                    value="{% if request.user.last_name %}{{ request.user.last_name }}{% endif %}"
                    name="last_name" id="id_last_name" required placeholder="Введите фамилию">
                </div>

                <div class="infBlock">
                    <label for="id_email" class="infTitle">Почта</label>
                    <input type="text" class="infInput" 
                    value="{% if request.user.email %}{{ request.user.email }}{% endif %}"
                    name="email" id="id_email" required placeholder="Введите почту">
                </div>

                <div class="infBlock">
                    <label for="id_phone_number" class="infTitle">Телефон</label>
                    <input type="text" class="infInput" 
                    value="{% if request.user.phone_number %}{{ request.user.phone_number }}{% endif %}"
                    name="phone_number" id="id_phone_number" required placeholder="Введите телефон">
                </div>

                <div class="profileTitle">Адрес доставки</div>

                <div class="profileInfContainer">

                    <div class="infBlock">
                        <label for="id_region" class="infTitle">Облать/Край/Регион</label>
                        <input type="text" class="infInput" 
                        value="{% if request.user.region %}{{ request.user.region }}{% endif %}"
                        name="region" id="id_region" required placeholder="Введите Облать/Край/Регион">
                    </div>

                    <div class="infBlock">
                        <label for="id_city" class="infTitle">Город</label>
                        <input type="text" class="infInput" 
                        value="{% if request.user.city %}{{ request.user.city }}{% endif %}"
                        name="city" id="id_city" required placeholder="Введите город">
                    </div>

                    <div class="infBlock">
                        <label for="id_street" class="infTitle">Улица, дом, квартира</label>
                        <input type="text" class="infInput" 
                        value="{% if request.user.street %}{{ request.user.street }}{% endif %}"
                        name="street" id="id_street" required placeholder="Введите улицу/дом/квартиру">
                    </div>

                    <div class="infBlock">
                        <label for="id_postcode" class="infTitle">Почтовый индекс</label>
                        <input type="text" class="infInput" 
                        value="{% if request.user.postcode %}{{ request.user.postcode }}{% endif %}"
                        name="postcode" id="id_postcode" required placeholder="Введите почтовый индекс">
                    </div>

                </div>
                <button type="submit" class="save">Сохранить</button>
                {% csrf_token %}
                {% if form.email.errors %}
                <ul class="errorlist nonfield" id="ErrorForm4">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </form>
        </div>

        <div class="tab profileMyOrders">

            <div class="profileTitle">Мои заказы</div>
            <table class="profileMyOrdersContainer">
                <thead>
                    <tr class="myOrdersTitleContainer">
                        <th class="myOrdersTitle">Заказ</th>
                        <th class="myOrdersTitle">Дата заказа</th>
                        <th class="myOrdersTitle">Статус</th>
                        <th class="myOrdersTitle">Стоимость</th>
                    </tr>
                </thead>
                <tbody class="bucketOrdersContainer">
                {% if orders %}
                {% for order in orders %}

                    <tr class="order">
                        <td class="orderNumber">№{{ order.id }}
                            <div class="modalOrder">
                                <h3 class="modalOrderTitle">Содержимое:</h3>
                                <ul class="modalOrderUl">
                                    {% for item in order.orderitem_set.all %}
                                        <li>{{ item.product.product_name }}</li>
                                    {% endfor %}
                                </ul>
                            <div>
                        </td>
                        <td class="orderDate">{{ order.created_timestamp }}</td>
                        <td class="orderStatus">{{order.status}}</td>
                        <td class="orderPrice" 
                        data-currency-rub="{{ order.orderitem_set.total_price }} р."
                        data-currency-usd="{{ order.orderitem_set.total_usd_price }} $"></td>
                    </tr>

                {% endfor %}
                {% else %}
                    <td colspan="4">У вас нет заказов :(</td>
                {% endif %}
                   
                </tbody>
            </table>
        </div>

        <div class="tab profilePasswrd">
            <div class="profileTitle">Смена пароля</div>
            <div class="profilePasswrdSettContainer">
                <form action="{% url 'сhangePass' %}" method="post" id="passChangeModal">
                    <div class="infBlock">
                        <label for="id_old_password" class="infTitle">Старый пароль</label>
                        <input type="password" class="infInput" 
                        name="old_password" id="id_old_password" required>
                    </div>
                    <div class="infBlock">
                        <label for="id_new_password1" class="infTitle">Новый пароль</label>
                        <input type="password" class="infInput"  
                        name="new_password1" id="id_new_password1" required>
                    </div>
                    <div class="infBlock">
                        <label for="id_new_password2" class="infTitle">Подтвердите пароль</label>
                        <input type="password" class="infInput" 
                        name="new_password2" id="id_new_password2" required>
                    </div>
                    <button type="submit" class="save">Сохранить</button>
                    {% csrf_token %}

                    {% if form.errors %}
                    <ul class="errorlist nonfield" id="ErrorForm5">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </form>
            </div>
        </div>


        <div class="tab profileAdditSett">
            <div class="profileTitle">Дополнительные настройки</div>
            <div class="profileAddirSettContainer">
                <div class="blockSetts">
                    <div class="titleBlockSetts">Тема сайта</div>
                    <div class="contentBlockSetts">
                        <div class="itemBlockSetts theme lightTheme" id="lightButton"><img class="iconSetts" src="{% static 'main/img/icon setts/icon_light_theme.png' %}" alt="светлая тема">Светлаяㅤ</div>
                        <div class="itemBlockSetts theme darkTheme activeTheme" id="darkButton"><img class="iconSetts" src="{% static 'main/img/icon setts/icon_dark_theme.png' %}" alt="темная тема">Темнаяㅤ</div>
                    </div>
                </div>
                <div class="blockSetts">
                    <div class="titleBlockSetts">Валюта</div>
                    <div class="contentBlockSetts">
                        <div class="itemBlockSetts currency rubCurrency activeCurrency" id="rubButton"><img class="iconSetts" src="{% static 'main/img/icon setts/icon_ruble.png' %}" alt="рубли">Рублиㅤ</div>
                        <div class="itemBlockSetts currency usdCurrency" id="usdButton"><img class="iconSetts" src="{% static 'main/img/icon setts/icon_dollar.png' %}" alt="доллары">Долларыㅤ</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'main/js/profile.js' %}"></script>
{% endblock  %}}