shop/carts/urls.py
from django.urls import path
from carts import views
from django.conf.urls.static import static

app_name = 'carts'
    
urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

shop/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from shop import settings
from django.contrib.auth.views import PasswordResetConfirmView
    
urlpatterns = [
    path('MEGAadmin/', admin.site.urls),
    path('', views.home, name='home'),
    path('faq', views.faq, name='faq'),
    path('registration', views.registration, name='registration'),
    path('login', views.login, name='login'),
    path('profile', views.profile, name='profile'),
    path('сhangePass', views.сhangePass, name='сhangePass'),
    path('password_reset/', views.passwordReset, name='password_reset'),
    path('password_reset/done/', views.home, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='main/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.home, name='password_reset_complete'),
    path('userInfo', views.userInfo, name='userInfo'),
    path('logout', views.logout, name='logout'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('category/<slug:category_slug>/', views.category, name='category'),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/carts/models.py
from django.db import models
from main.models import products, User

class CartQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_usd_price(self):
        return round(sum(cart.products_usd_price() for cart in self), 2)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0
    

class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Пользователь', default=0)
    product = models.ForeignKey(to=products, on_delete=models.CASCADE, verbose_name='Товар', default=0)
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'cart'
        verbose_name = "Корзина"
        verbose_name_plural = "Корзина"
        ordering = ("id",)

    objects = CartQueryset().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)
    
    def products_usd_price(self):
        return round(self.product.usd_sell_price() * self.quantity, 2)

    def __str__(self):
        return f'Корзина {self.user.username} | Товар {self.product.product_name} | Количество {self.quantity}'

shop/carts/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import redirect, render
from main.models import products
from carts.models import Cart
from carts.utils import get_user_carts

def cart_add(request):
    
    product_id = request.POST.get("product_id")
    product = products.objects.get(id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity +=1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)

    user_cart = get_user_carts(request)

    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request)

    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html,
    }

    return JsonResponse(response_data)

def cart_change(request):

    cart_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    cart = Cart.objects.get(id=cart_id)
    
    cart.quantity = quantity
    cart.save()
    updated_quantity = cart.quantity

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request)

    response_data = {
        "message": "Количество изменено",
        "cart_items_html": cart_items_html,
        "quantity": updated_quantity,
    }

    return JsonResponse(response_data)

def cart_remove(request):

    cart_id = request.POST.get("cart_id")

    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request)

    response_data = {
        "message": "Товар удален",
        "cart_items_html": cart_items_html,
        "quantity_deleted": quantity,
    }

    return JsonResponse(response_data)

shop/carts/templates/carts/includes/included_cart.html
{% load static %}
{% load carts_tags %}

{% user_carts request as carts %}

{% for cart in carts %}
    <div class="productAreaCart">

        {% if cart.product.img.url %}
            <img src="{{ cart.product.img.url }}">
        {% else %}
            <img src="{% static 'main/img/cart.svg' %}">
        {% endif %}
        
        <div class="productNameCart">{{ cart.product.product_name }}</div>
        
        {% if not order %}
            <div class="productCountAndPriceCart">
                {% if cart.quantity == 1 %}
                    <button type="button" class="btn delete"
                    data-cart-id="{{ cart.id }}"
                    data-cart-change-url="{% url "cart:cart_remove" %}">
                    {% csrf_token %}-</button>
                {% else %}
                    <button type="button" class="btn decrement"
                    data-cart-id="{{ cart.id }}"
                    data-cart-change-url="{% url "cart:cart_change" %}">
                    {% csrf_token %}-</button>
                {% endif %}
                
                <input type="text" class="numberProductsCart" value="{{ cart.quantity }}" readonly>
                
                <button type="button" class="btn increment"
                data-cart-id="{{ cart.id }}"
                data-cart-change-url="{% url "cart:cart_change" %}">
                {% csrf_token %}
                +</button>
                <span class="productPriceCart" 
                data-currency-rub=" {{ cart.products_price }} руб."
                data-currency-usd=" {{ cart.products_usd_price }} $">
                </span>
            </div>
        {% else %}
            <div class="productPriceCart" 
            data-currency-rub="{{ cart.quantity }} шт.* {{ cart.product.sell_price }} = {{ cart.products_price }} руб."
            data-currency-usd="{{ cart.quantity }} шт.* {{ cart.product.usd_sell_price }} = {{ cart.products_usd_price }} $">
        </div>
        {% endif %}

        {% if not order %}
            <a href="{% url "cart:cart_remove" %}"
            class="remove-from-cart"
            data-cart-id="{{ cart.id }}">
                {% csrf_token %}
                <img src="{% static 'main/img/delete.svg' %}">
            </a>
        {% else %}
        {% endif %}
    </div>
{% endfor %}
{% if carts and not order %}
    <div class="totalPriceCart" 
    data-currency-rub="Итого: {{ carts.total_price }} руб."
    data-currency-usd="Итого: {{ carts.total_usd_price }} $">
    </div>
    <div id="downCart">
        <div><a class="placeAnOrderCart" href="{% url 'orders:create_order' %}";>Оформить заказ</a></div>
    </div>
{% elif carts and order %}
    <div class="totalPriceCart" 
    data-currency-rub="Итого: {{ carts.total_price }} руб."
    data-currency-usd="Итого: {{ carts.total_usd_price }} $">
    </div>
{% else %}
    <div class="cartEmpty">Корзина пуста <span class="smile">-_-</span><span class="new-smile">\_/</span></div>
{% endif %}